clusters/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:specie>/', views.cluster, name='cluster'),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    path('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('clusters/', include('clusters.urls')),
    path('rice4869/', include('rice4869.urls')),
    path('admin/', admin.site.urls),
]

rice4869/urls.py
from django.urls import path

from . import views

app_name = 'rice4869'
urlpatterns = [
    path('', views.index, name='index'),
    path('view_detail/', views.view_detail, name='view_detail'),
    path('<str:gene_id>/', views.detail, name='detail'),
    path('<str:gene_id>/network/', views.network, name='network')
]

clusters/models.py
from django.db import models

# Create your models here.

rice4869/models.py
from django.db import models

# Create your models here.


class Imochi1(models.Model):
    gene_id = models.CharField(max_length=200)
    rddw_16h = models.IntegerField(default=0)
    rddw_24h = models.IntegerField(default=0)
    rddw_48h = models.IntegerField(default=0)
    rddw_72h = models.IntegerField(default=0)
    rmo_16h = models.IntegerField(default=0)
    rmo_24h = models.IntegerField(default=0)
    rmo_48h = models.IntegerField(default=0)
    rmo_72h = models.IntegerField(default=0)
    sddw_12h = models.IntegerField(default=0)
    sddw_24h = models.IntegerField(default=0)
    sddw_36h = models.IntegerField(default=0)
    sddw_48h = models.IntegerField(default=0)
    sddw_72h = models.IntegerField(default=0)
    smo_12h = models.IntegerField(default=0)
    smo_24h = models.IntegerField(default=0)
    smo_36h = models.IntegerField(default=0)
    smo_48h = models.IntegerField(default=0)
    smo_72h = models.IntegerField(default=0)

    def __str__(self):
        return self.gene_id

clusters/views.py
from django.shortcuts import render, get_object_or_404

def index(request):
    context = {
        'specie_list': ["Brapa","Arabidopsis","Ashtree","Bentham_v0_4_4","Buckwheat","Cacao","Carrot","Cassava",
                        "Coffee","Cucumber","Eucalyptus","Grape","Kiwifruit","Lettuce","Malus","Medicago","Monkeyflower",
                        "Olive","Orange","Papaya","Pepper","Poplar","Prunus","Soybean_a4v1","Spinach",
                        "Sugarbeet","Sunflower","Sweetpotato","Tomato_v2_4","Tomato_v3_2"],
    }
    return render(request, 'clusters/index.html', context)

def cluster(request, specie):
    return render(request, 'clusters/{}_cluster.html'.format(specie))

main/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'main/index.html')

rice4869/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, Http404
from .models import Imochi1
import numpy as np


def index(request):
    gene_list = Imochi1.objects.order_by('id')[:10]
    context = {
        'gene_list': gene_list,
    }
    return render(request, 'rice4869/index.html', context)


def detail(request, gene_id):
    gene_data = get_object_or_404(Imochi1, gene_id=gene_id)
    gene_list = Imochi1.objects.order_by('id')[:100]
    return render(request, 'rice4869/detail.html', {'gene_data': gene_data, 'gene_list': gene_list})


def network(request, gene_id):
    first_gene = get_object_or_404(Imochi1, gene_id=gene_id)
    all_gene = Imochi1.objects.order_by('id')
    all_gene_index = list(all_gene.values_list('gene_id'))
    all_gene = all_gene.values_list('rddw_16h', 'rddw_24h', 'rddw_48h', 'rddw_72h', 'rmo_16h', 'rmo_24h', 'rmo_48h', 'rmo_72h', 'sddw_12h', 'sddw_24h', 'sddw_36h', 'sddw_48h', 'sddw_72h', 'smo_12h', 'smo_24h', 'smo_36h', 'smo_48h', 'smo_72h')
    all_gene = np.array(all_gene)
    try:
        second_gene = get_object_or_404(Imochi1, gene_id=request.POST['second_gene'])
    except (KeyError, Imochi1.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'rice4869/detail.html', {
            'question': gene_id,
            'error_message': "You didn't select a choice.",
        })
    else:
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return render(request, 'rice4869/network.html', {'first': first_gene, 'second': second_gene, 'all': all_gene, 'index': all_gene_index})


def view_detail(req):
    if req.method == 'POST':
        gene = req.POST['select_gene']
        surprise_txt = gene + "!!!"

        response = {'your_surprise_txt': surprise_txt, }

        return JsonResponse(response)

    else:
        raise Http404

clusters/templates/clusters/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'clusters/style.css' %}" />
<link rel="stylesheet" href="{% static 'uikit.min.css' %}" />

<!-- jQuery is required -->
<script src="{% static 'jquery-3.2.1.min.js' %}"></script>

<!-- UIkit JS -->
<script src="{% static 'uikit.min.js' %}"></script>
<script src="{% static 'uikit-icons.min.js' %}"></script>

<meta name="viewport" content="width=device-width,initial-scale=1">
<title>NLR Clusters</title>
<link rel="shortcut icon" href="{% static 'main/images/favicon.ico'%}">
<link rel="icon" href="{% static 'main/images/favicon.ico'%}">
<div class="uk-container uk-width-auto uk-width-xxlarge@s">
  <div class="uk-card uk-card-default">
      <div id="top" class="uk-card-header">
          <div class="uk-grid-small uk-flex-middle uk-width-auto" uk-grid>
              <div class="uk-width-3-4@s">
                <div>
                    <img class="uk-align-left uk-margin-remove-bottom" src="{% static 'main/images/mychara.png'%}" width="64" height="64">
                    <p class="uk-card-title uk-margin-remove-bottom">Toshiyuki Sakai</p>
                    <h3 class="uk-text-meta uk-margin-remove-top">ID:slt666666</h3>
                </div>
                <div class="icon_links">
                    <a href="https://github.com/slt666666" class="uk-icon uk-margin-small-right" uk-icon="icon: github">GitHub</a>
                    <!-- <a href="http://slt666666.hatenablog.com/" class="uk-icon uk-margin-small-right" uk-icon="icon: pencil">Hatena</a> -->
                    <a href="https://twitter.com/slt666666" class="uk-icon uk-margin-small-right" uk-icon="icon: twitter">Twitter</a>
                    <a href="https://qiita.com/slt666666" class="uk-icon" uk-icon="icon: file-edit">Qiita</a>
                </div>
              </div>
          </div>
      </div>
      <div class="uk-card-body">
          {% if specie_list %}
          <p>* Recommend!! : Right-Click -> Save Link As ... </p>
          <p>(You can directly access to each link, but it takes long time...)</p>
          {% for specie in specie_list %}
          <a href="{{ specie }}" id="{{ specie }}" class="body-title">{{ specie }}</a><br>
          {% endfor %}
          {% else %}
              <p>No specie are available.</p>
          {% endif %}
      </div>
      <div class="uk-card-footer">
          <a href="#top" class="uk-icon-button uk-margin-small-right" uk-icon="icon: chevron-up" uk-scroll></a>
      </div>
  </div>
</div>

main/templates/main/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'main/style.css' %}" />
<link rel="stylesheet" href="{% static 'uikit.min.css' %}" />

<!-- jQuery is required -->
<script src="{% static 'jquery-3.2.1.min.js' %}"></script>

<!-- UIkit JS -->
<script src="{% static 'uikit.min.js' %}"></script>
<script src="{% static 'uikit-icons.min.js' %}"></script>

<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Toshiyuki Sakai (slt666666)</title>
<link rel="shortcut icon" href="{% static 'main/images/favicon.ico'%}">
<link rel="icon" href="{% static 'main/images/favicon.ico'%}">
<div class="uk-container uk-width-auto uk-width-xxlarge@s">
  <div class="uk-card uk-card-default">
      <div id="top" class="uk-card-header">
          <div class="uk-grid-small uk-flex-middle uk-width-auto" uk-grid>
              <div class="uk-width-3-4@s">
                <div>
                    <img class="uk-align-left uk-margin-remove-bottom" src="{% static 'main/images/mychara.png'%}" width="64" height="64">
                    <p class="uk-card-title uk-margin-remove-bottom">Toshiyuki Sakai</p>
                    <h3 class="uk-text-meta uk-margin-remove-top">ID:slt666666</h3>
                </div>
                <div class="icon_links">
                    <a href="https://github.com/slt666666" class="uk-icon uk-margin-small-right" uk-icon="icon: github">GitHub</a>
                    <!-- <a href="http://slt666666.hatenablog.com/" class="uk-icon uk-margin-small-right" uk-icon="icon: pencil">Hatena</a> -->
                    <a href="https://twitter.com/Toshi_666666" class="uk-icon uk-margin-small-right" uk-icon="icon: twitter">Twitter</a>
                    <a href="https://qiita.com/slt666666" class="uk-icon" uk-icon="icon: file-edit">Qiita</a>
                </div>
              </div>
              <div class="uk-card uk-card-default uk-card-body uk-width-1-4 uk-visible@s">
                <ul class="uk-nav-default uk-nav-center uk-nav-parent-icon" uk-nav>
                    <li><a href="#work" uk-scroll>Works</a></li>
                    <li><a href="#publish" uk-scroll>Publication</a></li>
                    <li><a href="#about" uk-scroll>About</a></li>
                </ul>
              </div>
          </div>
      </div>
      <div class="uk-card-body">
          <h3 id="work" class="body-title">Work, Program</h3>
          <ul class="uk-list uk-list-bullet">
              <li>Rice Coexpression Database</li>
              Co-expression analysis of Rice(Not yet)
              <li><a href="https://github.com/slt666666/RILStEp">RILStEp</a></li>
              Epistasis analysis for Recombinant inbred lines(RILs).
          </ul>
          <hr class="uk-divider-icon">
          <h3 id="publish" class="body-title">Publication</h3>
          <article class="uk-article">
              <li><a href="https://doi.org/10.1093/g3journal/jkab130">Sakai T, Abe A, Shimizu M, Terauchi R</a>
                RIL-StEp: epistasis analysis of rice recombinant inbred lines (RILs) reveals candidate interacting genes that control seed hull color and leaf chlorophyll content. G3 2021 doi: 10.1093/g3journal/jkab130</li>
              <li><a href="https://www.biorxiv.org/content/10.1101/2020.07.08.193961v2">Kourelis, J, Sakai, T, Adachi, H, and Kamoun, S</a>
                RefPlantNLR: a comprehensive collection of experimentally validated plant NLRs. bioRxiv 2021, doi: 10.1101/2020.07.08.193961.</li>
              <li><a href="https://www.biorxiv.org/content/10.1101/2020.10.12.333484v1">Adachi, H, Sakai, T, Kourelis, J, Maqbool, A, and Kamoun, S</a>
                Jurassic NLR: conserved and dynamic evolutionary features of the atypically ancient immune receptor ZAR1. bioRxiv 2020, doi: 10.1101/2020.10.12.333484.</li>
              <li><a href="https://www.biorxiv.org/content/10.1101/2020.06.17.157040v1">Ding P, Sakai T, Shrestha RK, Perez NM, Guo W, Ngou BPM, He S, Liu C, Feng X, Zhang R, Vandepoele K, MacLean D, Jones JDG</a>
                Chromatin accessibility landscapes activated by cell surface and intracellular immune receptors. bioRxiv 2020 doi: 10.1101/2020.06.17.157040</li>
              <li><a href="https://www.biorxiv.org/content/10.1101/2020.05.15.097584v1">Harant A, Sakai T, Kamoun S, Adachi H</a>
                A vector system for fast-forward in vivo studies of the ZAR1 resistosome in the model plant Nicotiana benthamiana. bioRxiv 2020 doi: 10.1101/2020.05.15.097584</li>
              <li><a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/pbi.13327">Ding P, Ngou BPM, Oliver J. Furzer OJ, Sakai T, Shrestha RK, MacLean D, Jones JDG</a>
                High-resolution Expression Profiling of Selected Gene Sets during Plant Immune Activation. Plant Biotechnol J. 2020 Jan 8. doi: 10.1111/pbi.13327</li>
              <li><a href="https://elifesciences.org/articles/49956">Adachi H, Contreras M, Harant A, Wu CH, Derevnina L, Sakai T, Duggan C, Moratto E, Bozkurt TO, Maqbool A, Win J, Kamoun S</a>
                An N-terminal motif in NLR immune receptors is functionally conserved across distantly related plant species. eLife 2019;8:e49956 doi: 10.7554/eLife.49956</li>
          </article>
          <hr class="uk-divider-icon">
          <h3 id="about" class="body-title">About</h3>
          <article class="uk-article">
              <p class="uk-text-lead">Education</p>
              <li>MSc, Kyoto University, Crop evolution lab, Japan</li>
              <li>(2019~) Visiting student, The Sainsbury Laboratory, Sophien Kamoun group, UK</li>
              <p class="uk-text-lead">Likes</p>
              <li>Python, Bioinformatics, Statistics, Machine Learning, Genomics, Boxing</li>
          </article>
      </div>
      <div class="uk-card-footer">
          <a href="#top" class="uk-icon-button uk-margin-small-right" uk-icon="icon: chevron-up" uk-scroll></a>
      </div>
  </div>
</div>

rice4869/templates/rice4869/detail.html
<h1>{{ gene_data.gene_id }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'rice4869:network' gene_data.gene_id %}" method="post">
{% csrf_token %}
{% for each_gene in gene_list %}
    <input type="radio" name="second_gene" id="each_gene{{ forloop.counter }}" value="{{ each_gene.gene_id }}" />
    <label for="each_gene{{ forloop.counter }}">{{ each_gene.gene_id }}</label><br />
{% endfor %}
<input type="submit" value="check" />
</form>

rice4869/templates/rice4869/index.html
<head>
{% load static %}
<!-- jQuery is required -->
<script src="{% static 'jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'rice4869/main.js' %}"></script>

</head>

{% if gene_list %}
    <!-- <ul>
    {% for gene in gene_list %}
        <li><a href="{% url 'rice4869:detail' gene.gene_id %}">{{ gene.gene_id }}</a></li>
    {% endfor %}
    </ul> -->
<h1>ajax test</h1>
<form id="gene_select_fm" action="{% url 'rice4869:view_detail'%}" method="post">{% csrf_token %}
    <select id="select_gene" name="select_gene">
    <option value="">遺伝子の選択肢</option>
    {% for gene in gene_list %}
    <option value="{{ gene.gene_id }}">{{ gene.gene_id }}</option>
    {% endfor %}
    </select>
    <button id="gene_select_btn" type="submit">send</button>
</form>
<div id="result">
</div>
{% else %}
    <p>No genes are available.</p>
{% endif %}

rice4869/templates/rice4869/network.html
<h1>{{ first.gene_id }}</h1>
<h1>{{ second.gene_id }}</h1>
{{ index }}
{{ all }}